### ISSUE TITLE
Gray mode for the theme

### ISSUE THREAD

**Issue by bhushan** [jiyuan0125/Github3#3]
I am big fan of this theme, if you could add gray mode as well it will be super cool 👌🏻

**Comment by bhushan** [comment]
https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme

 From this vscode theme you could get inspiration.. it is super cool

**Comment by jiyuan0125** [comment]
Thank you for your support. This proposal is great, and I also like the color scheme and contrast of GitHub Dark Dimmed. I will try it when I have free time.

**Comment by jiyuan0125** [comment]
[https://github.com/jiyuan0125/Github3/blob/master/Github3.jar](https://github.com/jiyuan0125/Github3/blob/master/Github3.jar)

I have submitted the dimmed theme, you can download and install it.

**Comment by bhushan-gaikwad** [comment]
![Screenshot 2021-08-04 at 11 12 53 AM](https://user-images.githubusercontent.com/83590083/128128199-69a947ce-b6a0-49aa-8a21-f537d7a918d6.png)

It has few issues but thnx for super fast response

**Comment by jiyuan0125** [comment]
Thank you for reporting this issue. For phpstorm, I just fixed some issues. Now you can try again.

**Comment by bhushan-gaikwad** [comment]
its much better, from morning I have switched to dimmed mode, getting used to it but i feel official colors are different in vscode theme

**Comment by jiyuan0125** [comment]
![image](https://user-images.githubusercontent.com/25894388/128273011-78fb6583-c8a3-40ff-afe1-2f991f2cfad5.png)

It is difficult to achieve 100% restoration, because different editors have different ways of dividing elements. In order for the color of a certain element to be consistent, it often affects the color definition of other elements. We can see that the theme on vscode is also different from the official one.

**Comment by bhushan** [comment]
Agreed. Thank you for awesome theme 🤘🏻
